/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

val ktor_version: String by project
val kotlin_version: String by project
val logback_version: String by project

group = "kozyriatskyi.anton.sked"
version = "0.0.1"

plugins {
    id("application-plugin")
    kotlin("plugin.serialization") version "1.6.10"
    id("application")
}

application {
    mainClass.set("kozyriatskyi.anton.sked.beckend.app.AppKt")
}

repositories {
    mavenCentral()
    maven { url = uri("https://maven.pkg.jetbrains.space/public/p/ktor/eap") }
}

dependencies {

    implementation(project(":sut-parser"))

    implementation("io.ktor:ktor-server-core:$ktor_version")
    implementation("io.ktor:ktor-server-netty:$ktor_version")
    implementation("io.ktor:ktor-html-builder:$ktor_version")
    implementation("io.ktor:ktor-serialization:$ktor_version")

    implementation("ch.qos.logback:logback-classic:$logback_version")

    testImplementation("io.ktor:ktor-server-tests:$ktor_version")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version")
}

application {
    // Define the main class for the application.
    mainClass.set("kozyriatskyi.anton.sked.beckend.app.AppKt")
}
