/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kozyriatskyi.anton.sked.beckend.app

import io.ktor.application.*
import io.ktor.features.*
import io.ktor.http.*
import io.ktor.response.*
import io.ktor.serialization.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import kotlinx.serialization.json.Json
import kozyriatskyi.anton.sked.beckend.routing.configureRouting

fun main(args: Array<String>) = EngineMain.main(args)

fun Application.mainModule() {
    configureSerialization()
    configureRouting()
    configureErrorResponses()
}

private fun Application.configureSerialization() {
    install(ContentNegotiation) {
        json(Json {
            prettyPrint = true
            isLenient = true
        })
    }
}

private fun Application.configureErrorResponses() {
    install(StatusPages) {
        exception<Throwable> {
            call.respond(HttpStatusCode.InternalServerError)
        }
    }
}